### ISSUE TITLE
Docs not work 

### ISSUE THREAD

**Issue by Cacsjep** [zunnzunn/vue-ganttastic#73]
online docs not work FYI

BR 

app.d4b712af.js:1 TypeError: Cannot read properties of null (reading 'parentNode')
    at remove (app.d4b712af.js:1:57258)
    at Object.remove (app.d4b712af.js:1:50036)
    at he (app.d4b712af.js:1:47160)
    at A (app.d4b712af.js:1:47777)
    at he (app.d4b712af.js:1:47048)
    at q (app.d4b712af.js:1:48013)
    at he (app.d4b712af.js:1:47206)
    at A (app.d4b712af.js:1:47777)
    at he (app.d4b712af.js:1:47048)
    at q (app.d4b712af.js:1:48013)
xc @ app.d4b712af.js:1

**Comment by zunnzunn** [comment]
You are probably referring to the problem of broken hyperlinks in the docs. I am aware of the problem, but haven't gotten the time to fix it yet. It only occurs in production when the docs are deployed to GitHub Pages. 

A simple workaround in the meantime: if you refresh the page once after loading it, the links should work.

**Comment by zunnzunn** [comment]
Fixed by #85
